# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "exyC5tINmpwjHvv4jajqS9Ef/hCb2J5N5LfstyLbMFXJ9c1Z8QE7JYwVFW9gQ+2teIYFWtbqjJfm3M1ghBh0UsiwGujSSH2J/i+u1EBkMBr9R3Gu8gdHIrc171++oE8iM9axkpUSiW+ri/HZFpLXnfYrqsnliAyFVlrfOLeQyeINRgKZyAn6HeItqYWqR0C9GWb9OWomK9vO3LMb0OV+E5DntEl8z+PRGIDJ1162V3IynCbl8P34sNn6ivbBW3E0R3364p4IMoJdb1UB+sE+u9PfO4Tm1exGABEBfxc4UJSDCZ3cHd3VD8EnaRLkVw+kiLfDOUCeXStLYpVg6rj/iqav5utoN/p6dAk8euBbD5UkCwpGwzTcH6ZSBCkGrxfcmeCgDEWXVCUQQe1eIHm55sEyNFGjJehdZPy1t511pI9aGdhtZvkFRQs0PzT6fnBS2tZKLP7A2VuuWC6DDCLlsqHeudJ1g37lSoK0YT/rdCst40rz9QlrjgrNVVi5Itsm2kBa0erOvzqqEzCb9ijR4W2k1FemrwjBzVCPyVZHSgZXSoVzqqrIbUi7s/FsGIF3b8uWA6oeScvJh47Q9hqTwy1cZHFO2ftTx2tQzeN1aIbufJucGPNTl4FAzb9yDM06NuK8/8gCjAARM8/t2ehiQlqt48xK1zasW+z9yZJbfRg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
