appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: exyC5tINmpwjHvv4jajqS9Ef/hCb2J5N5LfstyLbMFXJ9c1Z8QE7JYwVFW9gQ+2teIYFWtbqjJfm3M1ghBh0UsiwGujSSH2J/i+u1EBkMBr9R3Gu8gdHIrc171++oE8iM9axkpUSiW+ri/HZFpLXnfYrqsnliAyFVlrfOLeQyeINRgKZyAn6HeItqYWqR0C9GWb9OWomK9vO3LMb0OV+E5DntEl8z+PRGIDJ1162V3IynCbl8P34sNn6ivbBW3E0R3364p4IMoJdb1UB+sE+u9PfO4Tm1exGABEBfxc4UJSDCZ3cHd3VD8EnaRLkVw+kiLfDOUCeXStLYpVg6rj/iqav5utoN/p6dAk8euBbD5UkCwpGwzTcH6ZSBCkGrxfcmeCgDEWXVCUQQe1eIHm55sEyNFGjJehdZPy1t511pI9aGdhtZvkFRQs0PzT6fnBS2tZKLP7A2VuuWC6DDCLlsqHeudJ1g37lSoK0YT/rdCst40rz9QlrjgrNVVi5Itsm2kBa0erOvzqqEzCb9ijR4W2k1FemrwjBzVCPyVZHSgZXSoVzqqrIbUi7s/FsGIF3b8uWA6oeScvJh47Q9hqTwy1cZHFO2ftTx2tQzeN1aIbufJucGPNTl4FAzb9yDM06NuK8/8gCjAARM8/t2ehiQlqt48xK1zasW+z9yZJbfRg=}
bot:
  automerge: true
